### ISSUE TITLE
More detailed setup instructions

### ISSUE THREAD

**Issue by peterhartree** [Ocasio-J/SidecarLauncher#1]
Thank you for your work on this!

How exactly should this script be used? 

Here's what I tried:

1. Download the entire Github repo.
2. Extract the .zip
3. Open the directory in Terminal.
4. Run `./SidecarLauncher devices`

I get `zsh: permission denied`.

If I run `sudo ./SidecarLauncher devices` I get `sudo: ./SidecarLauncher: command not found`.

The contents of the directory I'm running these commands from:

<img width="236" alt="image" src="https://github.com/Ocasio-J/SidecarLauncher/assets/1412568/b9a07762-86ad-4d09-b8f6-bcaa1f422f61">

I also tried running the Shortcut via Shortcuts app, but it seems like the first `ssh` step is also failing, perhaps due to the `command not found`. 

It seems like I'm missing a step here?

Thanks in advance.

**Comment by jpazer** [comment]
I just ran into the same problem and got it to work. You need to open the downloaded folder in Xcode, then export it to an executable. Go to Product -> Archive -> Distribute. Then it will export it to an executable file. The path you need to link in the shortcut is the actual executable file and not a folder. Same with if you want to run any command line stuff.  And if you have any trouble with not being able to select from multiple devices I found I needed to add "" to the first two output statements to preserve the new line characters. (echo "$output")

**Comment by Ocasio-J** [comment]
SidecarLauncher is an executable, not a script. You can download the binary directly from https://github.com/Ocasio-J/SidecarLauncher/releases, or build it from source as @jpazer mentioned.
