### ISSUE TITLE
Add option to force connection via USB cable

### ISSUE THREAD

**Issue by peterhartree** [Ocasio-J/SidecarLauncher#4]
I always connect my iPad via USB cable, because, for me at least, the wifi version of Sidecar randomly disconnects at least once per hour (a lot of people report similar issues on various discussion forums).

When I run SidecarLauncher with the USB cable connected, the iPad still often connects via wifi. I'd love to have a way to force it to connect via USB.

(I wondered if I could solve this via System Settings, without the need to change SidecarLauncher. I've not been able to find a way to do this. Some internet discussion mentions that it's necessary to have your iPad's "Trust this computer" setting enabled; I have verified that I do.)

**Comment by Ocasio-J** [comment]
My motivation for SidecarLauncher is for when the iPad is away from the Mac. What's your use case here? If you're on USB, I assume you're already at your Mac, in which case just start SideCar as normal through Control Center?

**Comment by peterhartree** [comment]
I connect 5-10 times per day due to moving locations and (mainly) the frequent freezing/disconnection of Sidecar when it runs on WiFi. 

Given this, I really value having a simple keyboard shortcut to press when I wake my Mac from sleep, rather than an annoying three mouse clicks.

(To get a sense of "really value": I'd pay $30 / year for this.)

(On the frequent disconnections: I've never found a way to force Sidecar to run via USB, short of switching on Airplane mode on the iPad. This is pretty annoying because then I have to switch it off again when I use the iPad normally.)

**Comment by Ocasio-J** [comment]
There's a get/setDataLink method I see associated with a Sidecar device's config. Looks promising? 
But I'm sorry to say I probably won't look too much into this right now.

**Comment by LeiZHelpU** [comment]
I found a way that might force connection via usb cable ,you can download "Apple Configurator" app ,in the setting you can set to run the sidecarlauncher shortcuts when iPad is connected to mac  .also you might need to add 2 or 3 seconds delay to make sure that sidecar is connected via usb.   Then when you connect your ipad to your mac via cable it will enable sidecar automatically

**Comment by Ocasio-J** [comment]
When I connect my iPad to Sidecar wirelessly and then connect a USB cable, the iPad explicitly says "Switching to USB".
@peterhartree, can you possibly confirm this same behavior on your end?
If so, then I'll be curious to know if you experience any problems. If you do, then it'll mean that either (1) the USB connection itself can be just as unreliable as Wi-Fi (cheap cables/hubs maybe?) or (2) SideCar can silently transition from USB to Wi-Fi. If either case is true, then having a force USB option won't help as that would only apply to the **initiation** of the SideCar session.

Then there's the question of what connection method is chosen when the Mac wakes from sleep and automatically reconnects to SideCar.

**Comment by peterhartree** [comment]
Thanks for looking into this! I'm travelling this weekend, I'll get back to
you next week.

**Comment by peterhartree** [comment]
Here's the behaviour I see:

- USB cable connected => Activate SidecarLauncher => Sidecar via USB
- USB cable disconnected => Activate SidecarLauncher => Sidecar via Wifi
- USB cable disconnected => Activate SidecarLauncher => Sidecar via Wifi => Connect USB cable => Nothing happens (continues on Sidecar via Wifi)

It's interesting that you see different behaviour. My system details:

- MacBook 14-inch 2023 (M2 Pro); Sonoma 14.2.1  
- iPad Pro (6th generation); iOS 17.4.1.

When I created the ticket, I reported the following:

> I always connect my iPad via USB cable, because, for me at least, the wifi version of Sidecar randomly disconnects at least once per hour (a lot of people report similar issues on various discussion forums).
> 
> When I run SidecarLauncher with the USB cable connected, the iPad still often connects via wifi. I'd love to have a way to force it to connect via USB.

I'm happy to say that this roughly never happened to me in May. 

I'm using a different USB cable and working on a different Wifi network. I imagine there's also been some Mac / iOS updates during this period.

So—perhaps this feature is no longer needed.

I'll report back if I start seeing the issue again.

**Comment by Ocasio-J** [comment]
Interesting that you don't see the "Switching to USB" indicator. I'm on a M2 Mac Mini running Sonoma 14.5 and an iPad Air 5th Generation running iPadOS 17.5.1.

You also mentioned:

> Some internet discussion mentions that it's necessary to have your iPad's "Trust this computer" setting enabled; I have verified that I do.)

From what I understand, both devices need to trust each other, not just one way. Although I don't recall ever doing this.

Anyways, after some poking, I managed to successfully find an ugly way to force USB (or wireless). But the limitation is that the connection method is persistent. For example, once USB is forced, disconnecting the cable will not automatically transition to a wireless connection.

**Comment by peterhartree** [comment]
Oh cool! If, given what you now know, it's fairly easy to add a "force USB"
option to the script, then I'd vote in favour. Personally I *never* want to
connect via WiFi.

I believe my setup is that both devices trust each other.

Thanks for looking into this, and thanks again for making this script. I
run it via keyboard shortcut several times a day!
